version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  api:
    build:
      context: ../
      dockerfile: deploy/api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InspectionVisitsDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
      - Jwt__Key=dev_secret_key_change_me
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
volumes:
  sql_data:
